In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('StudentsPerformance.csv')

In [5]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [1]:
import os

python_path = r"C:\Users\hades\AppData\Local\Programs\Python\Python311\python.exe"

os.environ["PYSPARK_PYTHON"] = python_path
os.environ["PYSPARK_DRIVER_PYTHON"] = python_path

In [2]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .master("local[*]") \
    .appName("test") \
    .config("spark.python.worker.reuse", "false") \
    .getOrCreate()

sc = spark.sparkContext

In [7]:
df = spark.read \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .csv("run-1780539095637-part-r-00000.snappy")

df.printSchema()
df.show()

root
 |-- math_score: integer (nullable = true)
 |-- parental level of education: string (nullable = true)
 |-- race_ethnicity: string (nullable = true)
 |-- test_preparation_course: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- lunch: string (nullable = true)
 |-- reading_score: integer (nullable = true)
 |-- writing_score: integer (nullable = true)

+----------+---------------------------+--------------+-----------------------+------+------------+-------------+-------------+
|math_score|parental level of education|race_ethnicity|test_preparation_course|gender|       lunch|reading_score|writing_score|
+----------+---------------------------+--------------+-----------------------+------+------------+-------------+-------------+
|        47|         associate's degree|       group A|                   none|  male|free/reduced|           57|           44|
|        40|               some college|       group B|                   none|  male|free/reduced|           43|           39|
|        58|         associate's degree|       group C|                   none|  male|    standard|           54|           52|
|        40|         associate's degree|       group D|                   none|  male|    standard|           52|           43|
|        50|            master's degree|       group A|                   none|female|    standard|           53|           58|
|        18|           some high school|       group B|                   none|female|free/reduced|           32|           28|
|        46|            master's degree|       group C|              completed|  male|free/reduced|           42|           46|
|        44|               some college|       group D|                   none|  male|    standard|           54|           53|
|        40|               some college|       group D|                   none|  male|    standard|           42|           38|
|        57|         associate's degree|       group B|                   none|  male|free/reduced|           56|           57|
|        50|         associate's degree|       group E|                   none|female|free/reduced|           56|           54|
|        53|               some college|       group E|                   none|  male|    standard|           55|           48|
|        53|               some college|       group C|                   none|  male|    standard|           44|           42|
|        33|                high school|       group C|                   none|female|free/reduced|           41|           43|
|        52|         associate's degree|       group D|                   none|  male|    standard|           55|           49|
|        58|               some college|       group D|              completed|  male|    standard|           59|           58|
|         0|           some high school|       group C|                   none|female|free/reduced|           17|           10|
|        39|           some high school|       group A|                   none|  male|free/reduced|           39|           34|
|        59|           some high school|       group D|                   none|female|    standard|           58|           59|
|        45|           some high school|       group D|                   none|  male|free/reduced|           37|           37|
+----------+---------------------------+--------------+-----------------------+------+------------+-------------+-------------+
only showing top 20 rows

In [10]:
pandas_df = df.toPandas()

pandas_df.head()

,math_score,parental level of education,race_ethnicity,test_preparation_course,gender,lunch,reading_score,writing_score
0,47,associate's degree,group A,none,male,free/reduced,57,44
1,40,some college,group B,none,male,free/reduced,43,39
2,58,associate's degree,group C,none,male,standard,54,52
3,40,associate's degree,group D,none,male,standard,52,43
4,50,master's degree,group A,none,female,standard,53,58

In [15]:
pandas_df.columns

Index(['math_score', 'parental level of education', 'race_ethnicity',
       'test_preparation_course', 'gender', 'lunch', 'reading_score',
       'writing_score'],
      dtype='str')

In [17]:
pandas_df = pandas_df[
    [
        'gender',
        'race_ethnicity',
        'parental level of education',
        'lunch',
        'test_preparation_course',
        'math_score',
        'reading_score',
        'writing_score'
    ]
]

In [20]:
pandas_df.shape

(190, 8)

In [22]:
pandas_df.head()

,gender,race_ethnicity,parental level of education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,male,group A,associate's degree,free/reduced,none,47,57,44
1,male,group B,some college,free/reduced,none,40,43,39
2,male,group C,associate's degree,standard,none,58,54,52
3,male,group D,associate's degree,standard,none,40,52,43
4,female,group A,master's degree,standard,none,50,53,58

In [28]:
pandas_df.isna().sum()

gender                         0
race_ethnicity                 0
parental level of education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [30]:
pandas_df.groupby('race_ethnicity')[['math_score','reading_score','reading_score']].count()

                math_score  reading_score  reading_score
race_ethnicity
group A          47.076923      47.653846      47.653846
group B          44.534884      47.813953      47.813953
group C          45.694915      48.423729      48.423729
group D          48.023810      50.095238      50.095238
group E          47.200000      49.200000      49.200000

In [31]:
pandas_df.groupby('race_ethnicity')[['math_score','reading_score','reading_score']].mean()

                math_score  reading_score  reading_score
race_ethnicity
group A          47.076923      47.653846      47.653846
group B          44.534884      47.813953      47.813953
group C          45.694915      48.423729      48.423729
group D          48.023810      50.095238      50.095238
group E          47.200000      49.200000      49.200000